### ISSUE TITLE
for skill rolls, provide a way to save frequently rolled skill checks as new macros

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#11]
http://onlinedungeonmaster.com/2012/03/14/maptool-creating-macros-from-macros-plus-encode-and-decode/   createMacro(macroProps)

perhaps the default roller could be a pulldown to choose the skill, but a [] save checkbox would generate a new macro and add it to this token.

**Comment by trey-kirk-sp** [comment]
Did it in Issue #6
