### ISSUE TITLE
Allow GM to indicate which map to start on

### ISSUE THREAD

**Issue by havoclad** [mr-ice/maptool-macros#127]
Based on this post, it should be possible to force the initial map PC shows up on when they connect https://forums.rptools.net/viewtopic.php?f=6&t=28757

Could this be a GM preference to select?

**Comment by trey-kirk-sp** [comment]
Easy-peasy, on Lib:DnD5e:

[ ] - Add macro that allows the DM to specify the landing map. This seems like it outta be a GM Panel macro. Pipe up if you prefer Campaign panel
[ ] - Landing map macro sets a property on the library with the map name
[ ] - Add  [h:setCurrentMap("Landing Map Name")] in onCampaignInit

**Comment by trey-kirk-sp** [comment]
Fixed w/ hash 0c6689d2eb2. New GM macro added (imported in both Open5e and DNDBeyond GM macsets) that allows the GM to specify the landing map. Inbound players will be routed to that map. GMs are not affected.
