### ISSUE TITLE
importing monster from open5e results in index out of range

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#137]
selected token, ran "Setup Monster Token" from GM panel, searched for monster, found 1 result, clicked "Ok" on the Solar.

Argument index 4 out of range (max of 3) in function "arg".

**Comment by trey-kirk-sp** [comment]
Introduced in hash a08fbdae:

```[h: noAdvDisadvMacros = if(argCount() > 4, arg(4), 0)]```

Using the 'if' function (as opposed to the 'if' roll) won't work here since all parameters are evaluated.
