### ISSUE TITLE
Open5e import - don't change name please

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#148]
On Open5e "Setup Monster Token" the name on the token is overwritten.  This is annoying when the tokens already have names.  Could prompt, but better maybe is just don't do it.

**Comment by trey-kirk-sp** [comment]
Tell me more about what your monster token flow is. The intent of the framework was for something like:

- init the monster
- make customizations (including name, if desired)
- Ctrl+C / Ctrl+V ad nauseum

Ala, the initialization crates a template and you go from there. The optimal flow being you could go straight from template to play without any modification. But if you can describe to me how your flow goes, I can add behavioral preferences.

**Comment by mr-ice** [comment]
Well, I'm brand spanking newly adopting the open5e import, so unfortunately the flowus interruptus is that I have a monster token with custom macros, but I want all the open5e goodness, so I "Setup Monster Token" and it imports the goodness and sets the name.

But I already had a name.

When I did this to four at the same time, it prompted for monster names and verification on all four, no problem (expected and I was already set up with copy/paste).  But then it set the names all to the same string, which meant more touching.  And of course the popups obscured this fact until all four were done.

I agree that if I didn't already have a populated map your flow would be more appropriate.

**Comment by trey-kirk-sp** [comment]
How about we add a check box on the input to, when checked, retains the token's existing name. Extra clock, but saves some work. Can make it "sticky"also, so that when you're importing multiples, the check state will persist from token to token.

**Comment by mr-ice** [comment]
Sounds like a good compromise.

**Comment by trey-kirk-sp** [comment]
I've been thinking about this one and, in addition to wrapping the behavior in preferences, but also perhaps a good approach would be to set the GM Name instead. Maybe that's just another choice one may make.
