### ISSUE TITLE
Illusory Dragon - wrong save

### ISSUE THREAD

**Issue by havoclad** [mr-ice/maptool-macros#150]
Should be an intelligence save

<img width="266" alt="Screen Shot 2020-11-11 at 8 10 04 PM" src="https://user-images.githubusercontent.com/9877645/98886646-1309d480-245a-11eb-9992-337750dd0de1.png">

**Comment by trey-kirk-sp** [comment]
Tough to address. DnDBeyond is sending the trash:

```"saveDcAbilityId": 5``` (Which is Wis. Int would be '4')

Probably a good time to figure out a "patch" mechanism that will fix data defects like this with "known defects". Already have a clunky version of that with a player customization hook that doesn't have much exposure. Could build off of that idea.

**Comment by trey-kirk-sp** [comment]
Hey! Time to put that patched object bullshit to work!

**Comment by trey-kirk-sp** [comment]
Meh, the spell is technically correct. Upon casting, 
"any of your enemies that can see it must succeed on a Wisdom saving throw or become frightened of it for 1 minute."

And as a subsequent bonus action, 
"you can cause it to exhale a blast of energy in a 60-foot cone originating from its space. ... Each creature in the cone must make an Intelligence saving throw, taking '7d6 damage of the chosen damage type on a failed save, or half as much damage on a successful one."

So this is a spell with two distinct effects: A fear effect upon casting and a breath weapon attack as a later bonus action. The spell macros don't have any notion of "cast spell and do this effect; later do this different effect." And for spells like Illusory Dragon, the meat of the spell is in the breath weapon and not as much in the fear effect. I'll move forward with remapping the save to Int.
