### ISSUE TITLE
DnDBeyond - Spells! How do they work?

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#17]
So far spells have been merely an after-thought. Eventually, "after" will become "now".

What do we fetch? Spell slots seem obvious (used and available). Actual spell details, tho? Should probably include building a Spell Attack. Also, find out what kind of spell modifications could be granted through class and item features.

**Comment by havoclad** [comment]
Ketdelle's firebolt cantrip is the only spell that shows up on the Attack tab for me.  I guess the others I use "Magic Missile" and "Acid Splash" don't have attack rolls.  Perhaps that's why they don't.

If needed I could add a custom attack for you to experiment with parsing on.  Character 8035705 BTW

**Comment by coloneldork** [comment]
Bhelduhr has ball rot/chill touch and scorching ray

**Comment by trey-kirk-sp** [comment]
For the casting spell macro, it should:
- prompt for spell and expended spell level. Expended spell level is an optional choice which defaults to the minimum allowed spell slot for the selected spell.
- The  output should be the spell description, including save DC and related damage rolls
- Could be extended to include racial actions, like Dragonborn's Breath Weapon

**Comment by trey-kirk-sp** [comment]
Spells that show up as attacks are likely to correlate to those where definition.attackType is non-null (1 = melee, 2 = ranged. There are others to decode). I can collect objects where attackType is non-null and build attacks from them. Current attack logic will have to decouple ability from attackType to allow things like Charisma be the basis for a ranged attack, for instance.

Spells have a definition.modifier object that define the base damage as well as damage at higher levels. We'll have to refer to modifiers.atHigherLevels.scaleType to determine what levels its referring to. Ala, Firebolt has increased damage at higher _character_ levels while Fireball has increased damage at higher _spell_ levels. Need to find out what other possibilities there might be for modifiers.atHigherLevels.scaleType.

Might have to design a new attack builder, one that configures and enacts the attack. It can construct from Weapons, natural attacks, spells, and whatever else makes sense. The output should include:

- An attack roll, if required, with advantage or disadvantage applied
- A damage roll, including critical damage
- A save DC (type and save effect)
- Damage type

Continuing on the current pattern of saving configurable macros as personal discrete macros, we can still save the action as a personal macro. Should consider some convenient organization, like categorizing weapon attacks together or by categorizing spell attacks together and by expended spell slot.

Cramming all of this configuration into one dialog will be rather busy. Perhaps a wizard-style input is warranted. Ala, prompt one is, "Spell, weapon, natural ability". Prompt two could be the existing weapon config, or a new spell attack config, or a new breath weapon (for example) attack config.

Two main tasks to do:
- Build a Spell DTO
- Redesign Attacks

**Comment by mr-ice** [comment]
Is Spell, Weapon, Natural Ability on a dialog (three clicks) better than having a separate macro to initiate each (one click)?  Given that there aren't dozens of these like there are dozens of combinations at the next level.

A wizard would be better if you didn't have to 'next' 'next' when there is only one decision on the page.


+1 to organization though.

Should you also consider spells that are weapon attacks (Booming Blade, Green Flame Blade)?  Maybe you've already considered this?

**Comment by trey-kirk-sp** [comment]
Well it certainly could be multiple macros that configure a common "Attackable" which is passed to a common execution macro. That's exactly how Skills and Saves work currently. I'll keep that in mind.

I'm guessing those spells you cited will be exposed when I reconcile what things have non-null attackType. Otherwise I'll have to read up on those spells to figure how to incorporate their attacks.

**Comment by mr-ice** [comment]
https://www.dndbeyond.com/spells/booming-blade
https://www.dndbeyond.com/spells/green-flame-blade

They have the language "As part of the action used to cast this spell, you must make a melee attack with a weapon against one creature within the spell’s range, otherwise the spell fails." - SCAG may have more than a few of these -- all I know is Jon uses the crap out of them.

**Comment by trey-kirk-sp** [comment]
Goddamn fucking Bhelduhr! Of course he's got a class that can't cast spells, but then has a sub class that does. 

So the "Bhelduhr Bug": if classes.definition.canCastSpells is false, look for a subclassDefinition.canCastSpells to override. I suppose I should consider the other case of when subclassDefinition.canCastSpells is false when the default is true. Anybody know of a class where the sub-class removes spell casting? I feel like there's a Paladin sub-class that does that...

**Comment by trey-kirk-sp** [comment]
Note: Test on a Warlock. I'm sure that class is one giant curve ball.

**Comment by trey-kirk-sp** [comment]
With this issue I'm also adding a new object type: RollExpressions. These are objects that provide a more detailed way to make one roll of one type of die. A given action, like a weapon attack or a spell attack would normally be done with an array of RollExpressions. Typically one for the attack and one for the damage. Bonus damage could be rendered as a third RollExpression. RollExpressions also include Tags which describe additional behavior the roll should take (like if it's critable damage, if it's a d20 that could use advantage, if the dice should be rolled individually). Tags can also define where the roll is displayed (to the GM, publicly, to one's self)

This allows us to create a DiceRoller macro which will handle all RollExpressions. This will centralize where all dice rolling happens from the DNDB macros. The DiceRoller can later be extended to read user preferences, like showing the exploded rolls. It could also handle formatting either by the calling macro or the user.

Prototypes:
```
{
    "rollExpressions1": [
        {
            "name": "Scimitar Attack",
            "diceSize": "20",
            "diceRolled": "1",
            "bonus": "10",
// The tag "Advantagable" would tell the roller to look for 'hasAdvantage'/'hasDisadvantage'
            "tags": ["Advantagable"],
            "hasAdvantage": "false",
            "hasDisadvantag": "false"
        },
        {
            "name": "Damage",
            "diceSize": "6",
            "diceRolled": "1",
            "bonus": "8",
// Tells the roller we can roll again on a crit roll
            "tags": ["Critable"],
// Tells the roller this isn't the standard crit roll and instead, use this expression
            "onCritAdd": {
                "diceSize": "6",
                "diceRolled": "3"
            },
// Tells the roller which RollExpression will the critical be read from
            "onCritFrom": "0",
            "description": "Magic, Slashing"
        }
    ],
    "rollExpressions2": [
        {
            "name": "Fireball",
            "diceSize": "6",
            "diceRolled": "8",
// Description can contain save information for spells
            "description": "Fire damage. Dexterity save DC16 for half."
        }
    ],
    "rollExpressions3": [
        {
            "name": "Rapier",
            "diceSize": "20",
            "diceRolled": "1",
            "bonus": "8",
            "tags": [
                "Advantagable",
// Some tags won't impart any additional tags to read, just implied behavior; Tells the roller to re-roll 1s
                "Lucky"
            ],
            "hasAdvantage": "true"
        },
        {
            "name": "Damage",
            "diceSize": "8",
            "diceRolled": "1",
            "bonus": "8",
            "tags": ["Critable"],
            "onCritFrom": "0",
            "description": "Piercing"
        },
        {
            "name": "Sneak Attack",
            "diceSize": "6",
            "diceRolled": "5",
            "tags": ["Critable"],
            "onCritAdd": {
                "diceSize": "6",
                "diceRolled": "5"
            },
            "onCritFrom": "0",
            "description": "Sneak Attack"
        }
    ],
    "rollExpressions4": [
        {
            "name": "Magic Missle",
            "diceSize": "4",
            "diceRolled": "1",
// tells the roller to roll 1d4+1 three times
            "totallRolls": "3",
            "bonus": "1"
        }
    ]
}
```

**Comment by trey-kirk-sp** [comment]
RollExpression:
- create a rollType property that is an array of descriptors of the roll. Could be damage types or some other types I haven't thought of. 
- Change 'tags' to 'expressionTypes'; a RollExpression can be of multiple types, including Attack, Damage, Save, and Ability, including the other interfaces like Critable, Lucky, etc. Types can infer other interfaces, like Attack, Damage, Save, and Ability could all infer Advantagable.
- Remove "onCritFrom" property and instead apply a rule that any Critable roll will defer to a previously rolled Attack type expression. I don't have a use case for a RollExpression that would have two attack rolls. Two attacks should be two separate calls to the DiceRoller with different RollExpressions. So no need to try and disambiguate in that case.
- Create a "totals" property which works just like the "rolls" property. This is a ledger of totals, useful when totalRolls is > 1; Keep "total" and have it be a running tally of "totals". When a "Critable" is rolled, the second roll total is added as another element in the totals ledger. This will make it very easy to separate crit damage from regular damage.

**Comment by trey-kirk-sp** [comment]
Spells are done. It's a fresh turd that needs polishing, but it's feeling pretty functional.
