### ISSUE TITLE
embed instructions for the GM into project files

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#176]
to be rendered as console output, txt files, or html files

**Comment by mr-ice** [comment]
Need an input type, and a way to export that to txt and html.

* reStructured text
* markdown
* xml - ugh
* html - slightly less ugh, also slightly more ugh
* others?

primer on the differences between ReST and MD: https://www.jungledisk.com/blog/2017/01/20/restructuredtext-vs-markdown/

Any preferences?

markdown -- especially on github -- is pretty limited.  ReST has an unfortunate acronym.

**Comment by coloneldork** [comment]
I was only expecting text. Thinks like

- Install Lib:DnD5e token to a map used for library tokens
- Import DNDBeyond.mtmacset into the Campaign macro window
- import DND5e.mtprops into the Campaign Properties under the Edit menu

**Comment by mr-ice** [comment]
Really?  not super snazzy bullet lists but just:

```
- Install Lib:DnD5e token to a map used for library tokens
- Import DNDBeyond.mtmacset into the Campaign macro window
- import DND5e.mtprops into the Campaign Properties under the Edit menu
```

**Comment by mr-ice** [comment]
Fixed and closed in the dev-164 branch, soon to come to master.
