### ISSUE TITLE
DnDB - spell save ability is wrong 

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#179]
Ok, then the Lightning Bolt spell is screwed up, cause it shows 2 for save ability in basic_toon

**Comment by trey-kirk-sp** [comment]
For now, it's a 1-based list. I want to refactor it to act like everything else in dnd5e and make it 0-based. Should do that in #175

**Comment by coloneldork** [comment]
When you fix this update `dnd5e_AE2_typeDndbSpell`. Remove the `- 1` from line number 47
