### ISSUE TITLE
Reorganize the directory structure

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#20]
In PR #19 I complained about needing a better directory structure for how macros get broken out. Then I started complaining about an overall rethink of the directory structure and instead decided such a request should be in its own issue. So here:

Since I've brought up the topic of directory structure, is this a good time to ask this question: Could we re-think the current directory structure? Take my project for example:

- I have a library token in Lib-DnDBeyond/
- I have related campaign macros in DnDBeyond-macset/
- I build off of DND5e/'s mtprops
- Which requires the token library in Lib-DND5e/

What if we reorganized the directory structures into projects with the MT artifacts sub-directoried below? Where then we could have:

DnDBeyond/DnDbeyond-macset/
                  ./someOther-macset/ (Nothing to show as an example right now. Just a point of emphasis atm.)
                  ./Lib-DnDBeyond/

DND5e/mtprops/
          ./Lib-DnDBeyond/
         ./someFuture-macset/

Those random macros I made that didn't realize went into the macset I sent out a while back could live in a vanilla project folder?

**Comment by mr-ice** [comment]
You make a good point about OnCampaignLoad.  If there are vanishingly few of these they could be an exception (there should be at most one per rptok).

I'm hoping that we actually don't have other macros with the same name in this project -- at the same time, I'm hoping that new libraries can be built reusing macros without having to copy them to another spot in the repository to start a new history.

rptok and mtprops have lots of extras, so they'll be their own directories.  I can easily save the onCampaignLoad there.  

so a project artifact needs a properties, a list of tokens and a list of macros per destination (campaign, global, "other" token).

If we put the rptoks and mtprops directories per project, would you be comfortable still extracting the (non onCampaignLoad) macros to a common library directory?

**Comment by mr-ice** [comment]
If we eventually build all the rptoks, mtrpops, mtmacsets that we have inventory for, could a project be a manifest of which things go into it?

If we did that, would we somehow need to version them, so that project v0.9 would require tokenA v0.1 tokenB v1.1 propertiesA v0.7 etc?

**Comment by trey-kirk-sp** [comment]
> I'm hoping that new libraries can be built reusing macros without having to copy them to another spot in the repository to start a new history.

This is a bad idea. Suppose I develop  a library with macro 'doBusyWork' and Jay develops his own Campaign macro called 'doBusyWork'. When it comes to checking in the work, if neither of us is paying particular attention one's command will overwrite the other. Instead, if you want the ability for two libraries to rely on a common macro, create a third library for that macro and have both of them call that library macro instead.

**Comment by trey-kirk-sp** [comment]
> If we did that, would we somehow need to version them, so that project v0.9 would require tokenA v0.1 tokenB v1.1 propertiesA v0.7 etc?

Libraries do define their version, so I'm not opposed to this. From a git perspective, Tags could come into play here as well.

**Comment by mr-ice** [comment]
> > I'm hoping that new libraries can be built reusing macros without having to copy them to another spot in the repository to start a new history.
> 
> This is a bad idea. Suppose I develop a library with macro 'doBusyWork' and Jay develops his own Campaign macro called 'doBusyWork'. When it comes to checking in the work, if neither of us is paying particular attention one's command will overwrite the other. Instead, if you want the ability for two libraries to rely on a common macro, create a third library for that macro and have both of them call that library macro instead.


so the macros from a library (token) are always going to stay with that library and to move them one would need to move, not copy, them into another token?

Are you saying further that a macro export and a macset export should always be the owner of the particular macro(s) they contain?

**Comment by trey-kirk-sp** [comment]
> Are you saying further that a macro export and a macset export should always be the owner of the particular macro(s) they contain?

Correct! If I checkin a macset, it's because I intend those macros to be interrelated and should be treated as a single artifact. Consider the roll-outs:

Version 1:
"To install and use the DNDBeyond project, do the following:

1. Start with a base DND5e campaign
1. Drag the Lib-DNDBeyonnd.rptok onto any map
1. Import DNDBeyond.macset to your campaign macros"

This has one point of possible human error, which is the macset could be imported to the wrong pane. This is a limitation of MapTools and what we have to live with. It's not actually that bad if the macros are written to be flexible in how they look for other macros.

or

Version 2:
"To install and use the DNDBeyond project, do the following:

1. Start with a base DND5e campaign
1. Drag the Lib-DNDBeyonnd.rptok onto any map
1. Import macro1.macro, macro8.macro, macro13.macro, and macro14.macro to your campaign macros"

While the filenames are unrealistic, they demonstrate the point that said macros will be buried in a list of macros that one would need to cherry-pick out. This makes it more error-prone as the user could miss one or two or even import the wrong ones. Of course, as I'm writing this I'm considering burying the campaign macros into the library and having onCampaignLoad set them up. But that's another thing entirely...


Neither are great options in my opinion, but Version 1 is the lesser of two evils of what we can do today.

**Comment by mr-ice** [comment]
I'm not advocating Version 2,

I'm advocating macro can be part of mtmacro, mtmacset, or rptok   So _also_ version 1, but without having to maintain the arbitrary mtmacset that is exported from the Export Macro Set option, which only ever gives you all of them.

Instead, you export whatever you've got, but when we build we specifically build a mtmacset from a specified list.   So make a mtmacset.xml file without macros in it, but with the names of macros.

That's the direction I was going.  I was just extrapolating to rptokens, but maybe I'm starting to come around on tokens.  If you put them in a library token you have to call them with that tokens' name, right?   Would there ever be a cause to take a single macro from a token and put it on your global?

**Comment by trey-kirk-sp** [comment]
Yes, when a token macro is called, it has to be effective called ala "macro@token". I'm not sure one would ever want to migrate a library macro to be a stand-alone macro as the whole intent behind token libraries is to define macros called by other macros. Were I to write a library maco that could stand-alone, I would rethink why I put it in the library in the first place.

As to stand-alone tokens. My current project has three macros intending to be on the campaign pane: "Quick Update", "Reset Properties", & "Initialize". In your model, they will sit together with other sibling stand-alone macros. I assume at build time, they would be wrapped up together in an mtmacset to be ready for deployment. Keeping in mind I wouldn't want any of the other sibling macros to be included in this macset, what will control this packaging step? Will I, the developer, be able to control that directive or is it left up to the builder to figure out?

**Comment by mr-ice** [comment]
> I assume at build time, they would be wrapped up together in an mtmacset to be ready for deployment. Keeping in mind I wouldn't want any of the other sibling macros to be included in this macset, what will control this packaging step? Will I, the developer, be able to control that directive or is it left up to the builder to figure out?

I think that's what we're working out.

Right now on PR #19 there is a way to synthesize a mtmacset just by saying which macros you want in it.

So the ideas would be:

1. the build uses commands that correctly pulls the macros into the macset
2. the build uses a directive (such as a file with a list of macro names) to build a macset
3. the build uses a manifest to build all the "things" that go with this.  

In 3. the idea of a project with tokens, properties, and macsets is preserved.    We just need to work out how to specify what parts to build for each project, and the layout of the repo to accommodate that.

To build a mtmacset today, you need two things:  1) the name of the mtmacset to create (literally the base of the filename) and  2) the list of macros to include.

Since mtmacsets are unordered lists of macros, I just build a <list/> container and stick them in it then build the zip around that.   I can build any of those to individual mtmacro files becuase they're the same thing with only one macro and no <list/>

I think we have two different types of tokens.  Lib: tokens and generic tokens.  We may want to extract macros from the latter into macro/ but in the former case keep them with it.  I can do that based on the naming convention of Lib:.

**Comment by mr-ice** [comment]
What do you think about defining a project with an xml file like:
````
<project>
  <properties name="DNDBeyond"/>
  <token name="Lib-DNDBeyond"/>
  <macroset name="DNDBeyond">
    <macro name="Initialize"/>
    <macro name="Quick Update"/>
    <macro name="Reset Properties"/>
  </macroset>
</project>
````

The output could be: 
DNDBeyond.mtprops
Lib-DNDBeyond.rptok
DNDBeyond.mtmacset

Given that the token and properties are directories with more content to assemble.

**Comment by trey-kirk-sp** [comment]
I could get onboard with that.

**Comment by mr-ice** [comment]
This is the updated project file I'll be building an assembler for:

````
<project>
  <properties name="DND5e"/>
  <token name="Lib-DNDBeyond"/>
  <token name="Lib-DND5e"/>
  <macroset name="DNDBeyond">
    <macro name="Initialize DNDBeyond Character"/>
    <macro name="Quick Update"/>
    <macro name="Reset Properties"/>
  </macroset>
</project>
````

**Comment by mr-ice** [comment]
With all that, are we good on this issue and back to #5 ?

**Comment by trey-kirk-sp** [comment]
carry on

**Comment by mr-ice** [comment]
Ok, based on discussion and PR #19 we have reorganized the directory structure.  I'll be reviewing that PR and merging and marking this issue resolved.
