### ISSUE TITLE
Monster database creation is mandatory prior to using Setup Monster Token from Open5e

### ISSUE THREAD

**Issue by havoclad** [mr-ice/maptool-macros#210]
<img width="365" alt="Screen Shot 2021-03-09 at 2 03 38 PM" src="https://user-images.githubusercontent.com/9877645/110530600-42ff7680-80e0-11eb-9d4b-1ca8dd2f1105.png">

To reproduce, start a server with a new build from hash a168011 with no previous monster database.

Run Setup Monster Token prior to Create Ext Database

**Comment by trey-kirk-sp** [comment]
Think I fixed this in #110.

**Comment by trey-kirk-sp** [comment]
Fixed w/ #110
