### ISSUE TITLE
Wrong damage for Bode when hitting a black pudding

### ISSUE THREAD

**Issue by havoclad** [mr-ice/maptool-macros#212]
The black pudding took 13 damage (85 to 72).  But as no details were given on the output, I can't say how that was determined.

The pudding should have taken nothing from the slashing (despite it being magical).  But possibly something from the poison, but not 13.

<img width="361" alt="Screen Shot 2021-03-09 at 6 47 48 PM" src="https://user-images.githubusercontent.com/9877645/110558434-224b1700-8108-11eb-884e-2db17f0fc903.png">

**Comment by trey-kirk-sp** [comment]
This is the "immune damage results in 1" bug. In the original use case, Black Ooze (apparently) failed the save for poison and took 12 damage, plus 1 more for the immune slashing damage. In my test:
 
![image](https://user-images.githubusercontent.com/6287933/111255653-76ad3580-85e5-11eb-8a03-02d69ff039b1.png)

Black Ooze took a total of 5 points of damage: 4 for saving vs poison and 1 for the immune slashing attack. We know about the "immune == 1" bug but haven't logged it yet, so this will be that. This should also cover better reporting of the result. The state of the attack is kept and we know what happened. Seems silly it's not reporting anywhere.

**Comment by trey-kirk-sp** [comment]
Looks like we were being too ambitious with vulnerabilities always applying at least 1 point of damage and including the minimum 1 w/ immunities as well.

Also, how awesome is my new log library!? Nailed the bug within 5 minutes just by being able to trace exactly, and only, what I needed!

![image](https://user-images.githubusercontent.com/6287933/111327289-42646400-863b-11eb-9cb7-efe648c7dd9c.png)
