### ISSUE TITLE
DarkerDungeon: Healing on campaign with usable on token

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#213]
I don't like the healing being on Campaign but the usable being on the token -- and the usable doesn't actually roll the healing.

Further, when it reduces, I have both a @d8 and @d6 macro, it self-replicates but rolling the @d8 that remains shows its really a d6.

Rolling it when it's empty gives "Macro-defined error: Flask of Healing is Empty" guess that's ok except for the "Macro-defined error:" bit

**Comment by trey-kirk-sp** [comment]
> I don't like the healing being on Campaign but the usable being on the token 
Probably not a big deal to add an extra step in Usage_input to do a "create if not exist" macro

> Further, when it reduces, I have both a @d8 and @d6 macro, it self-replicates but rolling the @d8 that remains shows its really a d6.

I'm not reproducing this. That is, I've not found a way that the macro generates  a second copy of the usable. I can create a copy of the macro button leaving one to remain "d8" while the other correctly counts down.

> Rolling it when it's empty gives "Macro-defined error: Flask of Healing is Empty" guess that's ok except for the "Macro-defined error:" bit

Super easy to address.

**Comment by trey-kirk-sp** [comment]
Addendum to this issue: ggddH_healingPotion has a campaign property clash:
```
[h: hitDice = json.path.read(basicToon, "classes[*].hitDice")]
[h: hitDie = math.listMax(json.toList(hitDice))]
[h: log.debug (getMacroName() + "##hitDice = " + hitDice)]
```
'hitDice' is a campaign property. If one uses a healing option in Darker Dungeon, one's Hit Dice might look like:
![image](https://user-images.githubusercontent.com/6287933/117206994-181c6080-adb9-11eb-854e-47c3ba5f57cd.png)
