### ISSUE TITLE
When extracting a token also extract properties into its own file

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#218]
Token properties are tucked away in an element <propertyMapCI>. I'd like to be able to provide a default template for the store so that my development token's trash properties won't get saved.

**Comment by mr-ice** [comment]
hrm.. 

Does this fit better on 'extract' than 'assemble'?

**Comment by trey-kirk-sp** [comment]
Sure, why not?

**Comment by mr-ice** [comment]
Well, I just need specificity.

On extract we could do it with commandline options to the extract tool.  But this means you'd need to save those yourself to run it with those options each time (a .sh/.cmd file for example).

On assemble, we are swiftly moving to an xml based dsl in addition to commandline options, so you may be asking to add this to the .project file.

So is this a tool to keep "development token's trash properties" out of the `assemble`d asset, or out of the `extract`ed filesystem files that go into git?

And if the answer is "both", we might need some additional work on the project file ala #164 .

**Comment by trey-kirk-sp** [comment]
I envisioned having a template of what I want the properties to look like in the Token. That would be something that would be auto assimilated into the token by way of that template just existing within the token's extracted filesystem. It could be an XML format, but exist in a manner that excludes it from being interpreted as a macro XML definition file.

Making it a configuration in the project isn't my favorite choice, but if I had to, I could make that work. In which case, I would want to define a project just for the token and reference that project in other projects I want to include the token within. If we get to that, I'm really gonna want to explore what level of PITA it is to store project files for tokens within the extract directory of that token.

**Comment by mr-ice** [comment]
> something that would be auto assimilated into the token by way of that template just existing within the token's extracted filesystem

When?

so new token downloaded from maptool, but you have a list of templates.  At what point are the templates applied to the new token?  Can you point to the drawing and show me where it hurts?

![DevFlowDrawing](https://user-images.githubusercontent.com/1105176/110960939-dfaa5a00-8314-11eb-8625-071f4a2449ce.png)

**Comment by trey-kirk-sp** [comment]
I'm being more complicated than I need to be. How's this:

Let's just make token extraction also extract properties into its own file. Assemble incorporates that property file into the assembling token. I'm a big-boy git user and can protect the extracted property file from being overwritten with dev shenanigans just like I do with any other macro .command & .xml.

**Comment by mr-ice** [comment]
that I can do!

**Comment by mr-ice** [comment]
Are we talking about `<propertyMapCI>...</propertyMapCI>`?  This has things like abilities and `HP`, `Character ID`, etc...

Should we do the same with `<lastPath>...</lastPath>` and `<state>...</state>`?  Those can't be interesting to save in git either.   Those may be more interesting to blank out.   Let me know what you think.

**Comment by trey-kirk-sp** [comment]
Yes, <propertyMapCI/>. Those other elements are less interesting, but perhaps someday in the future that might change. I'm ambivalent as to what we do with them.

**Comment by mr-ice** [comment]
```
   Given I have a token to extract
    When I extract that token
    Then I should have a "propertyMapCI.xml" in the token directory
     And the propertyMapCI on the token content.xml should be empty
```

**Comment by mr-ice** [comment]
```
   Given I have a token to assemble
    And that token has a "propertyMapCI.xml" in the token directory
    When I assemble that token
    Then I should have a "propertyMapCI" element the token
```
