### ISSUE TITLE
Crit gives too much damage

### ISSUE THREAD

**Issue by havoclad** [mr-ice/maptool-macros#222]
Regular long sword attack created with Action Editor.  Damage is 1d8+3.  I confirmed this with regular hits.

It shouldn't hit 20 or 22 on a critical.

<img width="475" alt="Screen Shot 2021-03-13 at 10 52 24 PM" src="https://user-images.githubusercontent.com/9877645/111057720-42077580-844f-11eb-8082-4c7116caa6a5.png">

**Comment by havoclad** [comment]
<img width="534" alt="Screen Shot 2021-03-13 at 11 38 34 PM" src="https://user-images.githubusercontent.com/9877645/111058589-43d43780-8455-11eb-8519-e9f6bca0d449.png">

Consistently off?  Damage on this is 2d6+2, a crit of 24 is possible, but not the way the breakdown shows.

Instead of doubling the dice, it appears to be also tripling the additional damage.

**Comment by trey-kirk-sp** [comment]
Something jacked up in the rollers. Built a generic roll and get a +8 bonus out of nowhere on crit.

**Comment by trey-kirk-sp** [comment]
DR_critRoll is re-rolling the damageable RE with the 'weapon' & 'ability' types left on. This causes the respective ability bonus to be included when we merge the crit roll back into the parent roll. Ala, when DR_critRoll rolls additional crit damage, it needs to roll a stripped down version of the damage RE. Specifically, it retains only the basic and damageable types..
