### ISSUE TITLE
attack editor attacks and raginator incompatibility

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#236]
The raginator +3 equipped
![image](https://user-images.githubusercontent.com/1105176/111408851-e08c1480-86a3-11eb-978b-57ef76c3d631.png)

The Barbarian Rage (also +3) equipped
![Screen Shot 2021-03-16 at 10 01 31 PM](https://user-images.githubusercontent.com/1105176/111408925-031e2d80-86a4-11eb-8f34-702c2bd57cde.png)

Without either equipped:
![image](https://user-images.githubusercontent.com/1105176/111408998-1cbf7500-86a4-11eb-8712-e778fd33c9dc.png)

**Comment by trey-kirk-sp** [comment]
https://www.dndbeyond.com/profile/Mr__Ice/characters/46617638

**Comment by mr-ice** [comment]
[Atumash.rptok.zip](https://github.com/mr-ice/maptool-macros/files/6153551/Atumash.rptok.zip)

**Comment by trey-kirk-sp** [comment]
Two bugs have collided and made a bigger, stupider, child bug:
- Quick update doesn't seem to fully update attacks. (work around: Full init still does)
- Attack Editor is clearly massaging the Attack JSON that's "fixing" something. So private macros don't work great after update until Attack Editor does whatever it's doing. (Work around: after update, launch Action Editor & Save)

**Comment by trey-kirk-sp** [comment]
- [ ] Check ranged attacks, they're looking weird

**Comment by trey-kirk-sp** [comment]
Druid's have a ganked weapon proficiency problem. Their proficiencies are enumerated by weapon name explicitly where we've been looking for weapon proficiencies by category only. E.g., we're good at getting proficiencies for "Martial" and "Simple" weapons. Less good at getting proficiencies for "Longbow" and "Javelin".
