### ISSUE TITLE
DnD5e - Damage Rolls should have a minimum of 1

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#246]
1. Init Rex (20170550)
2. Attack w/ Unarmed Strike
3. Observe 0 points of damage

![image](https://user-images.githubusercontent.com/6287933/111850497-77441580-88de-11eb-8a45-6c92815a4987.png)

**Comment by havoclad** [comment]
There is no minimum damage rule in 5e per the [Sage Advice Compendium](https://media.wizards.com/2020/dnd/downloads/SA-Compendium.pdf).

> **Can damage be reduced to 0 by resistance or another form of damage reduction?** 
>There is no damage minimum in the rules, so it is possible to deal 0 damage with an attack, a spell, or another effect
