### ISSUE TITLE
I want to configure where the hash is stored on a token

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#252]
Currently, the hash is displayed on the GM field, which makes for a long token label:

![image](https://user-images.githubusercontent.com/6287933/112017004-370dae80-8afb-11eb-8528-09d838f73847.png)

My own preference is actually if were on the Label field:

![image](https://user-images.githubusercontent.com/6287933/112017175-602e3f00-8afb-11eb-9b59-3f60defa8e11.png)

It'd be nice if I had a build configuration that let's me designate where to put this value. Other choices might be the Notes, GM Notes, or even a property. But I'd consider those optional requirements.

**Comment by mr-ice** [comment]
Related to #183

**Comment by mr-ice** [comment]
Currently thinking the project will look something like:

```

<project>
    <token name="Lib-Log4MT" gitTagElement="label"/>
    [...]
</project>
```

The problem I'm making for myself is: what if your project includes another, or another includes yours?  Only tokens tagged with gitTagElement will have them, and only the first instance of a token is kept.   So, it's a teensy bit fragile where it shows up.
