### ISSUE TITLE
DND5e - Do better formatting in the Stat Sheet

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#29]
Values can include newlines which could make some busier properties better formatted. Consider the conditions as they are, could look like:

![image](https://user-images.githubusercontent.com/6287933/84618621-573b7d80-ae98-11ea-8cb3-7138ce8c34a9.png)

Notice the Conditions are creating one long line. After adding a couple of new lines, looks less like a single run-on sentance:

![image](https://user-images.githubusercontent.com/6287933/84618587-44c14400-ae98-11ea-9a7b-6fb408504e9e.png)

Might be a good place to also design other properties w/ compound statistics (example is the prototype "Senses" in the same screenshots.).

**Comment by havoclad** [comment]
wrapping is good!

**Comment by trey-kirk-sp** [comment]
Fixed in hash 66b05520
