### ISSUE TITLE
Player Preference for Initiative is missing

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#308]
![image](https://user-images.githubusercontent.com/6287933/115566754-267a6080-a280-11eb-8f92-bb27915b8d56.png)

Could've sworn I wrote a player preference to select the Initiative ability. It's there for the GM preference. Not sure how important this is to fix since:

1. This is probably a campaign-wide type of change, anyways. No use case jumps out at me for a class or race feature to have this changed on a per-PC basis
2. The Player can still manually update this via Token Properties and modifying 'ability.initiative'
3. I might need to fix #113 before this can even be done

**Comment by havoclad** [comment]
I don't know of a use case for this myself.  Init should be done campaign wide.
