### ISSUE TITLE
Attacks: Needs to be able to crit extra damage dice

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#31]
The bonus damage dice expression may be something that should be included in a crit. The right approach may simply be to include a flag to double the expression upon a crit.

Also, might be a good place to add a feature: Attack Config should allow creating a personal Make Attack for the created configuration.

Also also a good place to investigate extending programmatic determination of extra damage dice, like from Sneak Attack. Might be a mod with clear directives.

**Comment by trey-kirk-sp** [comment]
I think I'm finally going to have to step up my input game and build a versatile HTML input dialog that will allow 1..n damage expressions. The other important aspect is that the macro not only create attack expressions with this input, but edit existing expressions.

Todo:

- [ ] Refactor the Attack DTO to build RollExpressions map using attack names as keys; use a new key on the BasicToon to avoid clashes with the current attack macros

- [ ] Develop an html input with a more detailed and intuitive input

- [ ] Refactor Attack Config to read the new attack expressions and to leverage the HTML input

- [ ] Refactor Make Attack to leverage new attack expressions

**Comment by trey-kirk-sp** [comment]
One me thing to lump onto this issue: need to be more discrete about merging child rolls. The current pattern is that the Dice Roller will roll the children and then merge them all. Critical will add a new child, roll it, and then merge them all. There will be a problem it a Damage expression has a child at roll time and then crits, adding a second child for the crit. On the second merge, the first will get merged twice. Perhaps the best approach is to rethink how and when we total the roll values. Could instead defer calculation to getTotal

**Comment by mr-ice** [comment]
When refactoring this please also keep damage types separate and ensure they are output correctly (applies to non-crit damage as well).

**Comment by trey-kirk-sp** [comment]
re: Attack Config - At the end of the day, the only thing to do is to delete the OG macro in Lib:DnDBeyond. Trying to delete by name might catch the wrong macro(s). Clearing the Token group and rebuilding it from scratch might clobber user tokens. These are both very unlikely edge cases, but the alternative is that the user either never uses it or they delete it the first time they try to execute it and fail. New token inits will not get it.

**Comment by trey-kirk-sp** [comment]
Sneak Attack was pushed to #85. Otherwise covered the big rocks in this one. Current tests confirm known differences (spells and now attacks). Will reconcile the test objects in #53, but for now we're good.

Now for new tests:

- [ ] Launch Make Attack w/ no input and confirm the editor is launched.
- [ ] Launch Make Attack w/ input obj w/ action = save; Confirm no roll was made, object saved.
- [ ] Launch Make Attack w/ input obj w/ action = saveAttack; Confirm a roll was made, object saved.
- [ ] Create various data packages and pass them to the Attack Editor processor; Confirm upon call back the correct expression is built.
- [ ] Create attack expression w/ Damage, Save Damage, & Save Effect expressions. Roll them with static natural 20 and confirm only Damage expressions are processed as critical damage.
