### ISSUE TITLE
Atumash has incorrect initiative

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#323]
+0 instead of +1

**Comment by mr-ice** [comment]
I think I figured it out -- it's the darker dungeons stuff... I was looking at my DNDbeyond charsheet seeing the +1, which likely is Dex based, and the +0 in Pat's campaign is because it's Int based.    can the charsheet show +0 inititative (Int) for future dumbass me to be handed a clue?

**Comment by trey-kirk-sp** [comment]
Editing the Init shows what ability is being used to calculate it, IIRC. Is that sufficient?

**Comment by trey-kirk-sp** [comment]
In fact, it already does this:

![image](https://user-images.githubusercontent.com/6287933/116435138-aa988f00-a810-11eb-8275-1a0f0a7c3ae9.png)

The edit input also uses a Span to show the ability:

![image](https://user-images.githubusercontent.com/6287933/116435342-dc115a80-a810-11eb-9860-afd5f51bac3d.png)

But that's a nuance in a dialog that doesn't need such nuance. I can change the Input to clearly indicate the base ability. However, I'm letting the current display of the Initiative value remain as-is: floating over the bonus will show you the calculation, including the ability.

There is a defect where the span calculation doesn't include the bonus. Here is an initiative that has -1 Charisma, -3 Bonus and +10 (Expert) proficiency:

![image](https://user-images.githubusercontent.com/6287933/116435911-7b365200-a811-11eb-989d-e76cfbe3b9f0.png)

The value is correct, but the displayed calculation is missing a term.

**Comment by mr-ice** [comment]
Looks good to me, I'll verify in Pat's campaign next time and we'll all hope for a miracle of me not being confused again about this.
