### ISSUE TITLE
DNDB Macros have low standards

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#42]
The dndb_ macros are piling up and identifying them by name and function is becoming a challenge. They need to be refactored to use a naming convention that better classifies them. The 'dndb_' prefix could stay to continue to make 'onCampaignLoad' less of a hassle, but if that had to go it wouldn't be the worst thing in the world. I'm thinking something like this:

For Toon DTOs: (These are the macros that parse data directly off of the DNDBeyond character JSON and return an object intended for the BasicToon):
dndb_Toon_getWeapons
dndb_Toon_getSpells

This is a read-only object for us, is there anything that won't be a 'get'; Maybe use 'build' instead?

For BasicToon: (These are macros that retrieve the desired data from the BasicToon. Sometimes for the intent of applying them to the token, others to be used by macros)
dndb_BasicToon_applyHealth
dndb_BasicToon_getCastableSpells

For Utilities: (Most help with Toon parsing, but there may be a few that help with BasicToon)
dndb_Util_convertSpells
dndb_Util_createPlayerMacros

**Comment by coloneldork** [comment]
I didn't have too much problem figuring out what did what. There were just a lot of them. What if you made better use of the macro group for this? I know that only helps in MapTool. If you need it in the repository maybe we could get Mr. Ice to add directories to it for the groups...

**Comment by trey-kirk-sp** [comment]
Closing this down. We have a working pattern going forward and the existing stuff is "Don't fix what ain't broke"
