### ISSUE TITLE
Action macros for all this character data

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#6]
Once the player tokens are adorned with the data from DNDBeyond, we could implement macros for doing attacks, ability checks, saves, etc. Should consider some of this work may have already been done by the community at large, so take a look at existing solutions. Other considerations might be:

Presentation: present a form-like UI for related actions prompting the user for specifics? Ex. A dialogue with a selector of skills and ad-hoc modifiers. Or breaking down actions to be more atomic? Ex. One button for athletics checks, another for perception.

Application to tokens: do players have to start with a token implemented with these macros or can they import them into existing tokens.

**Comment by coloneldork** [comment]
There is a setMacroCommand() and setMacroProperties() that allow you to create macros on a token. Maybe we can use these in a 'populate' macro to generate all of the required macros on a PC or NPC.

**Comment by trey-kirk-sp** [comment]
From some discussion in issue #7, the idea of creating a quick update style macro came up that players can use to during game sessions for quick state updates. For now, that might only be hit points and conditions. Upon the resolution of #7, we might be able to expand on that. This includes the sub-task to create a Conditions DTO and abstract hit points into its own DTO.

**Comment by trey-kirk-sp** [comment]
Created a "Quick Update" campaign macro that currently will refresh Hit Points, AC, and speed. Of the things I'm pulling now, those hit the mark on the likelihood of fluctuating and ability to build quickly. We can expand on this macro (or even eliminate it) once the initializer performance improves.

Also added library macros that will be cloned as meta macros (wrappers) to the token. Those macros, in turn, can create new macros with explicit arguments. An example token macro panel might wind up looking like this:

![image](https://user-images.githubusercontent.com/6287933/84344149-9fdcf900-ab6f-11ea-9f63-5ec188b2ce8c.png)

I think one more useful token macro before calling this done would be a hit dice roller. We'll talk about spell rollers when we can actually build them.

**Comment by trey-kirk-sp** [comment]
Calling this good.
