### ISSUE TITLE
Project-assemble should declare dependency projects

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#67]
For example, DNDBeyond.project has a dependency to DND5e, but DNDBeyond shouldn't need to declare macrosets that would only require DND5e. To address that, today we could create a DND5e.project and define the macro set there. But what we need next is for DNDBeyond.project to reference DND5e.project so that when I build DNDBeyond, it includes DND5e.project automatically. Where both projects create macros sets, we should merge them into one macro set when the defined macro sets share the same name.

**Comment by mr-ice** [comment]
The project dependency is here, but the macroset merge is similar to #164 , keeping this one open to add this functionality

**Comment by mr-ice** [comment]
BilirubenToday at 8:43 PM
I think I would just simplify that requirement to say, merge the mtmacsets with common names. By way of Implementation, we can ensure one gm, one campaign, and one free-for-all whacky-ass player set.

**Comment by mr-ice** [comment]
Currently there is no state saved between sub-elements of the project

```
<project>
   <project "DND5e"/>    # may contain GM.mtmacset
   <project "DarkerDungeons"/> # may contain GM.mtmacset
   <macroset name="GM">
   [...]
```

I think I will have to actually merge the projects into a single project with all shared and unique members before building anything.  More xml fun!

**Comment by mr-ice** [comment]
Reopening, needed behave tests to make sure it's actually plugged in
