### ISSUE TITLE
We want a /build directory

### ISSUE THREAD

**Issue by trey-kirk-sp** [mr-ice/maptool-macros#68]
Leaving built artifacts in the repository root is annoying and clutters things up. It's a bit of a hassle to identify artifacts I've built when they are interspersed with build scripts and related files. We need a /build or /output or whateverly named directory where built artifacts are generated. I think that would also mean that *-extract scripts would have to be updated so that when executed, we can specify the build path as part of the artifact, ergo:

`$ dockerrun token-extract build/Lib-DNDBeyond.rptok`

...would extract in the desired source directory.

**Comment by mr-ice** [comment]
Yep, extract would need to have an override for the base directory .   Will it be acceptable for that to default to the current working directory?

I can't _easily_ use /build or /output as the default...   on the linux/macos systems that means something that you and I can't write to normally.

Where would we want the default to go? ./build or ./output is fine
