### ISSUE TITLE
can we auto-pop a monster from https://api.open5e.com/

### ISSUE THREAD

**Issue by mr-ice** [mr-ice/maptool-macros#95]
https://api.open5e.com/ has a lot of monsters at https://api.open5e.com/monsters/, for example https://api.open5e.com/monsters/imp

Found via https://tetra-cube.com/dnd/dnd-statblock.html

**Comment by trey-kirk-sp** [comment]
Yes, but some things aren't straight forward:

```
 {
                    "attack_bonus": 9,
                    "damage_dice": "3d8+6",
                    "desc": "Melee Weapon Attack: +9 to hit, reach 5 ft., one target. Hit: 19 (3d8 + 6) piercing damage.",
                    "name": "Gore"
                }
```
Doesn't conveniently separate damage type. But if it's consistent, regex could tease it out.
```
 "strength_save": null,
            "dexterity_save": null,
            "constitution_save": null,
            "intelligence_save": null,
            "wisdom_save": null,
            "charisma_save": null,
```
Saves are disappointing, but abilities can derive the base, which I assume is the intent. Look for examples where these are non-null and see if they're literal values or bonuses.

Should be in a new library (Lib:open5e?). If we build it in the same format as BasicToon, Reset Properties is a shoe-in to transfer token properties.

**Comment by trey-kirk-sp** [comment]
Also, DMs should chime in with what they might want to see on an NPC stat sheet. We can create a different Token type for these and show a different view of properties

**Comment by trey-kirk-sp** [comment]
Need a break from Lib:DnDBeyond. Let's see if I can screw this up...

**Comment by mr-ice** [comment]
> Saves are disappointing, but abilities can derive the base, which I assume is the intent.

I think so.  this is really only showing saves for which the monster has specials.  See https://api.open5e.com/monsters/frost-giant/

**Comment by havoclad** [comment]
Perhaps you already know this, but saves a monster is proficient in receive half their CR as a bonus (rounded down).

**Comment by mr-ice** [comment]
interesting, but I'm not seeing that on my frost giant example, nor this:
https://www.dndbeyond.com/monsters/frost-giant

**Comment by havoclad** [comment]
Huh, guess I had that slightly wrong.  Their proficiency bonus is determined by their CR, there's a table in the front of the monster manual.  CR6-CR8 is a +3

**Comment by trey-kirk-sp** [comment]
W/ Frosty as the use case, looks like calculation is not my problem. His API reports exactly what the value should be:

```
"constitution_save": 8,
    "intelligence_save": null,
    "wisdom_save": 3,
    "charisma_save": 4,
```

**Comment by mr-ice** [comment]
> Their proficiency bonus is determined by their CR

Correct:
"A saving throw bonus is the sum of a monster’s relevant ability modifier and its proficiency bonus, which is determined by the monster’s challenge rating (as shown in the Proficiency Bonus by Challenge Rating table)." https://dnd.wizards.com/products/tabletop/dm-basic-rules

the table referenced is just below that.

**Comment by mr-ice** [comment]
> looks like calculation is not my problem

Also correct.  The proficient saves are calculated for you, the non-proficient saves are straight ability modifier.

**Comment by havoclad** [comment]
My two cents, (worth diddly as a guy not coding much in this)
I'd rather this stuff had the brains, so when I go diddling with things, the numbers stay right.  IE, if I bump the wisdom, the save should go up.  If I alter the CR, changes flow thru, etc.

**Comment by trey-kirk-sp** [comment]
Goddammit, Pat

**Comment by trey-kirk-sp** [comment]
Search: https://api.open5e.com/monsters/?search=Gold%20Dragon
             https://api.open5e.com/monsters/?search=gold+dragon

Specific Monster: https://api.open5e.com/monsters/adult-gold-dragon/

Filter widget provides many other examples of searchables and ordering. Don't anticipate the macro should be so advanced. Thinking the nominal use case is a creature is already in mind and the user need only populate the token of that creature. So basic by-name search will do.

To accommodate "live" changes when abilities are adjusted, saves need to be derived. Something like:

Charisma Bonus: 4
Charisma Save: {CharismaBonus + ProfBonus}

But to accomplish this, we have to first:
- [ ] Remove white space from token properties; Give them display names that are human friendly: ex. CharismaBonus (Charisma Bonus): {Charisma / 2 - 5}
- [ ] Refactor Lib:DNDBeyond "Reset Properties" to adjust
- [ ] Set Skill and Save properties to {n + abilityBonus} where 'n' is either the literal value provided by open5e minus the relevant bonus or n is 0. This infers the proficiency bonus without having to be responsible for calculating it explicitly or anticipate double-prof and half-prof.

Actions (attacks) aren't so easy to associate to ability properties. Ideally we'd leverage already written macros, however they rely on an JSON expression with pre-built values. Perhaps this might be an opportunity to bring them closer to the state of the token.

**Comment by trey-kirk-sp** [comment]
User experience should be:
- Select target token
- Launch macro from GM panel
- Prompt for name. Search and when more than 1 found, return a list of names to pick
- From list prompt, user can either select a name or select "Back to Search" and OK to continue
- If zero results, return to the same prompt with an additional msg of what's not found
- When one is selected or exactly one is found, move forward with population
- Populated token now serves as a prototype; user can copy & paste for additional of the same type

**Comment by trey-kirk-sp** [comment]
There's some good stuff in the damage description that'd be really nice to pull out. Some examples
```
Melee Weapon Attack: +12 to hit, reach 5 ft., one target. Hit: 14 (2d6 + 7) slashing damage.
Melee Weapon Attack: +11 to hit, reach 15 ft., one target. Hit: 15 (2d8 + 6) bludgeoning damage.
Melee Weapon Attack: +13 to hit, reach 15 ft., one target. Hit: 18 (3d6 + 8) plus 3 (1d6) poison damage.
Ranged Weapon Attack: +9 to hit, range 150/600 ft., one target. Hit: 9 (1d8 + 5) piercing damage.
Ranged Weapon Attack: +6 to hit, range 150/600 ft., one target. Hit: 8 (1d8 + 4) piercing damage
```
This isn't an exhaustive list of all types of actions, but for the bread 'n butter attacks, there's an apparent pattern. I can regex this... probably.

**Comment by trey-kirk-sp** [comment]
In order to associate attacks to abilities such that a property change can adjust the next roll, the attack information has to be stored as just a data map that is is stripped of ability bonuses. At attack time, roll expression has to be built on the fly.

- [ ] Create parsing macro to marshal an action string into a JSON object.
- [ ] Create an Action macro to execute the action, passing in the JSON object
- [ ] Action macro combines the data w/ the current state of the token to build the appropriate expression; rolls it
- [ ] On Init, create token macros for each action; Skip known non-starters (like Multi-Attack)
- [ ] Extra credit: include the ole 'Edit' button for token macros that allows an attack to be edited in the Attack Editor. Means before launching the editor, the attack would have to be marshaled into an expression and on save, recombobulated back into its base data object.

**Comment by trey-kirk-sp** [comment]
TODO: against my better judgement, I'm getting good at regex in MT. So it shouldn't be too hard to:
- [ ] Parse and tokenize "senses": "blindsight 60 ft., darkvision 120 ft., passive Perception 24",
- [ ] Set token sight based on available matching sights
- [ ] Prune passive Perception and set the rest on the property "senses"

**Comment by trey-kirk-sp** [comment]
Coming together, but a few gaps:
- [ ] Save effects aren't parsed. Determine what pattern can read save DCs, abilities, and damage effects.
- [ ] Pull in latest master and incorporate Jay's new attack output to monster action rolls.

Push: 

- CR scaling will have to be more than changing a property. That will need its own macro
- Attack Editor will be on the token as an available macro to create custom attacks, but it will not be editing the same data for monster actions (aka attacks). In order to allow monster actions to pick up ability changes, the data format is incompatible with Attack Editor. Adapting DNDBeyond to use action data in the same manner, instead of static attacks, would help in getting DNDBeyond toon using "live" data. Once that's done, Attack Editor can be adapted to edit action data instead of roll expressions.

**Comment by trey-kirk-sp** [comment]
DMs are gonna want DC values restricted from the output. Create a preference that drives RollExpression_getSaveDC.

- [ ] Define a Campaign preference
- [ ] Have getSaveDC take an optional boolean argument to ignore the preference
- [ ] getSaveDC will return "" when the preference is enabled and the optional argument to ignore it is falsey; else it will return the value.

**Comment by trey-kirk-sp** [comment]
Bugs:
- [ ] baba-yagas-horsemen-black-night - Doesn't parse the attack action for Lance
- [ ] ghostwalk-spider - Double reads the poison effect
- [ ] giant-wolf-spider - Doesn't read the attack action, just damage
- [ ] ancient-silver-dragon - See if there's something we can do to read in the breath weapons as separate actions
- [ ] gargoctopus - Ink Cloud throws an error; Tentacle slam's string is a different format. How much churn would it take to parse it. Does it have a roll object associated?

**Comment by trey-kirk-sp** [comment]
A few more monsters to test with before claiming victory:

https://open5e.com/monsters/aboleth-nihilith
https://open5e.com/monsters/ankou-soul-herald
https://open5e.com/monsters/androsphinx
https://open5e.com/monsters/adult-void-dragon
https://open5e.com/monsters/adult-sea-dragon
https://open5e.com/monsters/adult-rime-worm

**Comment by trey-kirk-sp** [comment]
- [ ] - aboleth-nihilith - During search, the input is built incorrectly and shows a duplicate "Aboleth" in the list.
- [ ] - aboleth-nighilith - Save effect is the wrong text. Should be what's in the "token" key.
```
{
    "extraDamage": [
        {
            "start": 58,
            "end": 89,
            "token": " or become diseased. The disease has no effect for 1 minute; during that time, it can be removed by lesser restoration or comparable magic. After 1 minute, the diseased creature's skin becomes translucent and slimy. The creature cannot regain hit points unless it is entirely underwater, and the disease can only be removed by heal or comparable magic. Unless the creature is fully submerged or frequently doused with water, it takes 6 (1d12) acid damage every 10 minutes. If a creature dies while diseased, it rises in 1d6 rounds as a nihilethic zombie. This zombie is permanently dominated by the nihileth.",
            "saveDC": 14,
            "saveAbility": "Constitution",
            "averageDamage": 6,
            "damageRollObj": {
                "diceRolled": 1,
                "diceSize": 12,
                "bonus": ""
            },
            "damageType": "acid",
            "damageRollString": "1d12"
        },
        {
            "start": 58,
            "end": 89,
            "token": " or become diseased. The disease has no effect for 1 minute; during that time, it can be removed by lesser restoration or comparable magic. After 1 minute, the diseased creature's skin becomes translucent and slimy. The creature cannot regain hit points unless it is entirely underwater, and the disease can only be removed by heal or comparable magic. Unless the creature is fully submerged or frequently doused with water, it takes 6 (1d12) acid damage every 10 minutes. If a creature dies while diseased, it rises in 1d6 rounds as a nihilethic zombie. This zombie is permanently dominated by the nihileth.",
            "saveDC": 14,
            "saveAbility": "Constitution",
            "saveEffect": " every 10 minutes. If a creature dies while diseased, it rises in 1d6 rounds as a nihilethic zombie. This zombie is permanently dominated by the nihileth."
        }
    ]
}
```
- [ ] - adult-rime-worm Tendril parses as "Something Happens" macro
- [ ] - adult-rime-worm Black Ice Spray doesn't parse damage
- [ ] - Merge save DC data from the last extraDamage obj into the sibling damage objects (Void Dragon Stellar Flare Breath / Deathsworn Volley are examples of multi-damage that caused the current model)
